(define (sine-steps angle)
  (define steps 0)
  (define (cube x) (* x x x))
  (define (p x)
    (set! steps (+ 1 steps))
    (- (* 3 x) (* 4 (cube x))))
  (define (sine angle)
    (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))
  (sine angle)
  steps)

(display (sine-steps 12.15))
(newline)
