(load "3.serializer-mutex.scm")
(define (make-semaphore n)
  (let ((n-procs-gate (list false))
        (n-procs 0))
    (define (acquire)
      (if (test-and-set! n-procs-gate)
        (acquire)
        (if (= n-procs n)
          (begin
            (clear! n-procs-gate)
            (acquire))
          (begin
            (set! n-procs (+ n-procs 1))
            (clear! n-procs-gate)))))
    (define (release)
      (if (test-and-set! n-procs-gate)
        (release)
        (begin
          (set! n-procs (- n-procs 1))
          (clear! n-procs-gate))))
    (lambda (m)
      (cond ((eq? m 'acquire) (acquire))
            ((eq? m 'release) (release))
            (else (error "Unknown operation -- SEMAPHORE" m))))))
