;;;; 3.78
;; Consider the problem of designing a signal-processing system to study the homogeneous second-order linear differential equation
;;
;; $$ \frac{d^2y}{dt^2} - a\frac{dy}{dt} - by = 0 $$
;;
;; The output stream, modeling $y$, is generated by a network that contains a loop. This is because the value of $d^2 y / d t^2$ depends upon the values of $y$ and $dy / dt$ and both of these are determined by integrating $d^2 y / d t^2$. The diagram we would like to encode is shown in figure 3.35. Write a procedure `solve-2nd` that takes as arguments the constants $a$, $b$, and $dt$ and the initial values $y0$ and $dy0$ for $y$ and $dy/dt$ and generates the stream of successive values of $y$.

;;; Answer
(load "3.streams.scm")
(load "3.stream.solve.scm")
(define (solve-2nd a b dt y0 dy0)
  (define y (integral (delay dy) y0 dt))
  (define dy (integral (delay ddy) dy0 dt))
  (define ddy (add-streams (scale-stream dy a)
                           (scale-stream y b)))
  y)

;; ;; Test
;; (display (stream-ref (solve-2nd 0 -1 0.0001 1 0) 10472)) ; cf. seok (http://community.schemewiki.org/?sicp-ex-3.78)
