(define (monte-carlo trials experiment)
  (let iter ((trials-remaining trials)
             (trials-passed 0))
    (if (= trials-remaining 0)
      (/ trials-passed trials)
      (iter (- trials-remaining 1)
            (if (experiment)
              (+ trials-passed 1)
              trials-passed)))))
