(define (lookup-variable-value var env)
  (let env-loop ((env env))
    (if (eq? env the-empty-environment)
        (error "Unbound variable" var)
        (let scan-bindings ((frame (first-frame env)))
          (if (null? frame)
              (env-loop (enclosing-environment env))
              (let ((binding (first-binding frame)))
                (if (eq? var (var-binding binding))
                    (val-binding binding)
                    (scan-bindings (rest-bindings frame)))))))))

(define (set-variable-value! var val env)
  (let env-loop ((env env))
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- SET!" var)
        (let scan-bindings ((frame (first-frame env)))
          (cond ((null? frame)
                 (env-loop (enclosing-environment env)))
                ((eq? var (var-binding (first-binding frame)))
                 (set-binding-to-frame! var val frame))
                (else (scan-bindings (rest-bindings frame)))))))
  'ok)

(define (define-variable! var val env)
  (let ((frame (first-frame env)))
    (let scan-bindings ((curr-frame frame))
      (cond ((null? curr-frame)
             (add-binding-to-frame! var val frame))
            ((eq? var (var-binding (first-binding curr-frame)))
             (set-binding-to-frame! var val curr-frame))
            (else (scan-bindings (rest-bindings curr-frame))))))
  'ok)
