(define (scan-out-defines body)
  (let* ((def?
           (lambda (exp)
             (tagged-list? exp 'define)))
         (make-exp
          (lambda (defs rest)
            (append (map (lambda (x)
                           (make-definition (definition-variable x)
                                            '(quote *unassigned*)))
                         defs)
                    (map (lambda (x)
                           (make-assignment (definition-variable x)
                                            (definition-value x)))
                         defs)
                    rest))))
    (let loop ((exps body)
               (next (lambda (defs rest)
                       (if (null? defs) rest
                           (make-exp defs rest)))))
      (if (null? exps) (next '() '())
          (let ((exp (car exps)))
            (loop (cdr exps)
                  (lambda (defs rest)
                    (if (def? exp)
                        (next (cons exp defs) rest)
                        (next defs (cons exp rest))))))))))

(define (make-procedure parameters body env)
  (list 'procedure parameters (scan-out-defines body) env))
