(load "4.lazy.scm")
(load "4.metacircular.test.scm")
(global-eval '(define count 0))
(global-eval '(define (id x)
                (set! count (+ count 1))
                x))
(global-eval '(define w (id (id 10))))
(print-global-eval 'count)
(print (actual-value 'w the-global-environment)) ; Force value (cf. 4.lazy.driver.scm)
(print-global-eval 'count)
