(define genesis-data-base
  '((son Adam Cain)
         (son Cain Enoch)
              (son Enoch Irad)
                    (son Irad Mehujael)
                         (son Mehujael Methushael)
                                  (son Methushael Lamech)
                                            (wife Lamech Ada)
                                                    (son Ada Jabal)
                                                    (son Ada Jubal)))
