(define (install-preamble)
  (map global-eval
       '((define (require p)
           (if (not p) (amb)))
         (define (an-element-of items)
           (require (not (null? items)))
           (amb (car items) (an-element-of (cdr items))))
         (define (an-integer-starting-from n)
           (amb n (an-integer-starting-from (+ n 1))))
         (define (distinct? items)
           (cond ((null? items) true)
                 ((null? (cdr items)) true)
                 ((member (car items) (cdr items)) false)
                 (else (distinct? (cdr items)))))))
  'ok)
