;; Inherit
(load "4.12.mceval.scm")
;; Core
(load "4.analyzingmceval.eval.scm")
(load "4.analyzingmceval.apply.scm")
;; Expression types
(load "4.analyzingmceval.eval.self-evaluating.scm")
(load "4.analyzingmceval.eval.variable.scm")
(load "4.analyzingmceval.eval.quoted.scm")
(load "4.analyzingmceval.eval.assignment.scm")
(load "4.analyzingmceval.eval.definition.scm")
(load "4.analyzingmceval.eval.if.scm")
(load "4.analyzingmceval.eval.lambda.scm")
(load "4.analyzingmceval.eval.begin.scm")
(load "4.analyzingmceval.eval.load.scm")
(load "4.analyzingmceval.eval.cond.scm")
(load "4.analyzingmceval.eval.and-or.scm")
;; Setup
(define the-global-environment (setup-environment))
(install-self-evaluating-package)
(install-variable-package)
(install-quotation-package)
(install-assignment-package)
(install-definition-package)
(install-if-package)
(install-lambda-package)
(install-begin-package)
(install-load-package)
(install-cond-package)
(install-and-or-package)
(install-extras)
