;; Interface
(load "4.metacircular.procedure.scm")
(load "4.3.metacircular.application.scm")
(load "4.12.metacircular.frame.scm")
(load "4.12.metacircular.env.scm")
(load "4.12.metacircular.lookup.scm")
;;  Core
(load "4.analyze.eval.scm")
(load "4.analyze.apply.scm")
;; Setup
(load "4.metacircular.primitive.scm")
(load "4.metacircular.global.scm")
(load "4.metacircular.driver.scm")
(load "4.metacircular.extras.scm")
(load "4.metacircular.util.scm")
;; Packages
(load "0.table.scm")
(load "4.analyze.self-evaluating.scm")
(load "4.analyze.variable.scm")
(load "4.analyze.quotation.scm")
(load "4.analyze.assignment.scm")
(load "4.analyze.definition.scm")
(load "4.analyze.if.scm")
(load "4.analyze.lambda.scm")
(load "4.analyze.begin.scm")
(load "4.analyze.and-or.scm")
(load "4.analyze.cond.scm")
(load "4.22.analyze.let.scm")
(load "4.analyze.load.scm")
;; Install
(define the-global-environment (setup-environment))
(define *op-table* (make-hash-table))
(install-self-evaluating-package)
(install-variable-package)
(install-quotation-package)
(install-assignment-package)
(install-definition-package)
(install-if-package)
(install-lambda-package)
(install-begin-package)
(install-cond-package)
(install-and-or-package)
(install-let-package)
(install-load-package)
(install-extras)
