(load "4.lazy.scm")
(load "4.34.lazy-stream.history.scm")
(load "4.34.lazy-stream.lazy-pair.scm")
(load "4.34.lazy-stream.driver.scm")
(load "4.34.lazy-stream.util.scm")
(load "4.34.lazy-stream.cons.scm")
(load "4.33.lazy-stream.quotation.scm")
(load "4.lazy-stream.map-lists.scm")
(install-cons-package)
(install-quotation-package)
(install-map-lists-package)
