(define (setup-environment)
  (let ((initial-env
         (extend-environment (primitive-procedure-names)
                             (primitive-procedure-objects)
                             the-empty-environment)))
    (define-variable! 'nil '() initial-env)
    (define-variable! 'true true initial-env)
    (define-variable! 'false false initial-env)
    initial-env))

(define primitive-procedures
  (list (list 'car car)
        (list 'cdr cdr)
        (list 'caar caar)
        (list 'cadr cadr)
        (list 'cdar cdar)
        (list 'cddr cddr)
        (list 'caaar caaar)
        (list 'caadr caadr)
        (list 'cadar cadar)
        (list 'caddr caddr)
        (list 'cdaar cdaar)
        (list 'cdadr cdadr)
        (list 'cddar cddar)
        (list 'cdddr cdddr)
        (list 'caaaar caaaar)
        (list 'caaadr caaadr)
        (list 'caadar caadar)
        (list 'caaddr caaddr)
        (list 'cadaar cadaar)
        (list 'cadadr cadadr)
        (list 'caddar caddar)
        (list 'cadddr cadddr)
        (list 'cdaaar cdaaar)
        (list 'cdaadr cdaadr)
        (list 'cdadar cdadar)
        (list 'cdaddr cdaddr)
        (list 'cddaar cddaar)
        (list 'cddadr cddadr)
        (list 'cdddar cdddar)
        (list 'cddddr cddddr)
        (list 'member member)
        (list 'set-car! set-car!)
        (list 'set-cdr! set-cdr!)
        (list 'apropos apropos)
        (list 'pp pp)
        (list 'length length)
        (list 'cons cons)
        (list 'append append)
        (list 'list list)
        (list 'assoc assoc)
        (list 'null? null?)
        (list 'number? number?)
        (list 'string? string?)
        (list 'symbol? symbol?)
        (list 'pair? pair?)
        (list 'list? list?)
        (list '1+ 1+)
        (list '+ +)
        (list '- -)
        (list '* *)
        (list '/ /)
        (list '= =)
        (list '< <)
        (list '> >)
        (list 'abs abs)
        (list 'remainder remainder)
        (list 'modulo modulo)
        (list 'not not)
        (list 'eq? eq?)
        (list 'equal? equal?)
        ;; (list 'apply apply)
        (list 'memq memq)
        (list 'make-hash-table make-hash-table)
        (list 'hash-table/put! hash-table/put!)
        (list 'hash-table/get hash-table/get)
        (list 'display display)
        (list 'newline newline)
        (list 'print print)
        (list 'read read)
        (list 'read-file read-file)
        (list 'error error)
        (list 'bkpt bkpt)
        (list 'debug debug)
        (list 'exit exit)))
