;; Cons
(define (make-stack)
  (let ((stacks '())
        (cons-stack
         (lambda ()
           (let ((s '()))
             (lambda (m)
               (cond ((eq? m 'push)
                      (lambda (x)
                        (set! s (cons x s))))
                     ((eq? m 'pop)
                      (if (null? s)
                          (error "Empty stack -- POP")
                          (let ((top (car s)))
                            (set! s (cdr s))
                            top)))
                     ((eq? m 'initialize)
                      (set! s '())
                      'done)
                     (else
                      (error "Unknown request -- STACK" m))))))))
    (lambda (name)
      (let ((record (assoc name stacks)))
        (if record (cadr record)
            (let* ((new-stack (cons-stack))
                   (new-record (list name new-stack)))
              (set! stacks (cons new-record stacks))
              new-stack))))))
;; Interface
(define (pop stack)
  (stack 'pop))
(define (push stack val)
  ((stack 'push) val))
