(define (alist-make)
  (let* ((table (table-make))
         (keys-get (lambda () (table-get table 'keys))))
    (lambda (m)
      (cond ((eq? m 'keys) (keys-get))
            ((eq? m 'put)
             (lambda (head tail)
               (table-put-append-list table 'keys head)
               (table-put-append-list table head tail)
               'ok))
            ((eq? m 'get)
             (map (lambda (key) (list key (table-get table key)))
                  (keys-get)))
            (else
             (error "Unknown request -- alist" m))))))
(define (alist-keys alist)
  (alist 'keys))
