(define (flist-make)
  (let ((table (table-make)))
    (lambda (m)
      (cond ((eq? m 'put)
             (lambda (node)
               (let ((type (car node))
                     (val (cadr node)))
                 (table-put-append-list table type val)
                 'ok)))
            ((eq? m 'get)
             (map (lambda (key) (cons key (table-get table key)))
                  flist-keys))
            (else
             (error "Unknown request -- flist" m))))))
(define flist-keys '(reg stack const label op testop))
