;; Cons
(define (make-machine ops controller-text)
  (let ((machine (make-new-machine)))
    ((machine 'install-operations) ops)
    ((machine 'install-instruction-sequence)
     (assemble controller-text machine))
    machine))
(define (make-new-machine)
  (let ((pc (make-register 'pc))
        (flag (make-register 'flag))
        (stack (make-stack))
        (the-instruction-sequence '())
        (flist (flist-make))
        (alist (alist-make))
        (inst-count 0)
        (trace-inst false))
    (let ((the-ops
           (list (list 'print print)
                 (list 'initialize-stack
                       (lambda () (stack 'initialize)))))
          (register-table
           (list (list 'pc pc)
                 (list 'flag flag))))
      (define (allocate-register name)
        (if (assoc name register-table)
            (error "Multiply defined register: " name)
            (set! register-table
                  (cons (list name (make-register name))
                        register-table)))
        'register-allocated)
      (define (lookup-register name)
        (let ((val (assoc name register-table)))
          (if val (cadr val)
              (error "Unknown register: " name))))
      (define (execute)
        (let ((insts (get-contents pc)))
          (if (null? insts) 'done
              (let ((next-inst (car insts)))
                (when trace-inst
                  (print (instruction-label next-inst)
                         (instruction-text next-inst)))
                ((instruction-execution-proc next-inst))
                (execute)))))
      (define (dispatch m)
        (cond ((eq? m 'start)
               (set-contents! pc the-instruction-sequence)
               (execute))
              ((eq? m 'install-instruction-sequence)
               (lambda (seq) (set! the-instruction-sequence seq)))
              ((eq? m 'allocate-register) allocate-register)
              ((eq? m 'get-register) lookup-register)
              ((eq? m 'install-operations)
               (lambda (ops) (set! the-ops (append the-ops ops))))
              ((eq? m 'stack) stack)
              ((eq? m 'operations) the-ops)
              ((eq? m 'flist) flist)
              ((eq? m 'alist) alist)
              ((eq? m 'data-path-dot)
               (lambda (opts) (data-path-dot flist alist opts)))
              ((eq? m 'inst-count-reset)
               (set! inst-count 0))
              ((eq? m 'inst-count) inst-count)
              ((eq? m 'trace-on)
               (set! trace-inst true))
              ((eq? m 'trace-off)
               (set! trace-inst false))
              (else
               (error "Unknown request -- MACHINE" m))))
      dispatch)))
;; Interface
(define (start machine)
  (machine 'start))
(define (get-register-contents machine register-name)
  (get-contents (get-register machine register-name)))
(define (set-register-contents! machine register-name value)
  (set-contents! (get-register machine register-name) value)
  'done)
(define (get-register machine reg-name)
  ((machine 'get-register) reg-name))
(define (data-path machine . opts)
  ((machine 'data-path-dot) opts))
